---
# tasks file for winstackdrivers

- name: Download StackdriverLogging-v1-14
  win_get_url:
    url: https://storage.googleapis.com/binaries2/StackdriverLogging-v1-14.exe
    dest: C:\Users\Public\Downloads\StackdriverLogging-v1-14.exe

- name: Install Logging Agent
  win_shell: C:\Users\Public\Downloads\StackdriverLogging-v1-14.exe /S

- name: Download StackdriverMonitoring-GCM-46
  win_get_url:
    url: https://storage.googleapis.com/binaries2/StackdriverMonitoring-GCM-46.exe
    dest: C:\Users\Public\Downloads\
 
- name: Install Monitoring Agent
  win_shell: C:\Users\Public\Downloads\StackdriverMonitoring-GCM-46 /S
